name: "Bug Report"
description: "Create a report to help us resolve an issue."
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction Details"
      description: "An example of steps, code, or other minimal requirements to reproduce the issue."
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Any additional information to help explain the issue, including screenshots or videos."
    validations:
      required: false
  - type: input
  id: resource-version
  attributes:
    label: "Resource Version"
    description: "The version of the resource being used. You can find this in the fxmanifest."
    placeholder: "v1.2.3"
  validations:
    required: true
  - type: input
    id: server-version
    attributes:
      label: "FXServer Version"
      placeholder: "25770"
    validations:
      required: true
  - type: dropdown
    id: client-channel
    attributes:
      label: "Client Channel"
      multiple: true
      options:
        - Release
        - Beta
        - Canary
    validations:
      required: true
  - type: dropdown
    id: game
    attributes:
      label: "Game"
      multiple: true
      options:
       - FiveM (Legacy)
       - FiveM (Enhanced)
       - RedM
    validations:
      required: true
  - type: input
    id: server-listing
    attributes:
      label: "Server Listing"
      description: "If the issue occurs on a publicly accessible server, provide its server listing so we can investigate the environment."
      placeholder: "https://servers.fivem.net/servers/detail/xxxxxxx"
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
      - label: "I have verified that the issue persists without unrelated third-party resources."
        required: false
      - label: "I have verified that the issue persists when using the latest official release version of the resource."
        required: false
    validations:
      required: false
